protocol = "mcc152analogout"
doc = ""
traits = ["has-position", "has-limits", "is-daemon"]
hardware = ["mccdaq:mcc152", "raspberry-pi:4b"]

[links]
source = "https://github.com/yaq-project/yaqd-mcc"
bugtracker = "https://gitlab.com/yaq/mccdaq/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-mcc"

[config]

[config.address]
doc = "daqhat address"
type = "int"
default = 0

[config.terminal]
doc = "daqhat terminal"
type = "int"

[config.make]
doc = "make of the daqhat"
type = ['null', 'string']
default = "Measurement Computing Corporation (MCC)"

[config.model]
doc = "model of the daqhat"
type = ['null', 'string']
default = "MCC 152"

[state]

[messages]

[messages.get_address]
doc = "get board address"
response = "int"


