protocol = "mcc-118"
doc = ""
traits = ["has-measure-trigger", "is-sensor", "is-daemon"]
hardware = ["mccdaq:mcc118", "raspberry-pi:4b"]

[links]
source = "https://github.com/yaq-project/yaqd-mcc"
bugtracker = "https://github.com/yaq-project/yaqd-mcc/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-mcc"

[config]

[state]

[messages]

